import * as Yup from 'yup';
import {
  nomeSchema,
  descricaoSchema,
  urlImagemSchema,
} from 'common/utils/yupSchemas';

export const CARDFLUX_SCHEMA = Yup.object({
  nome: nomeSchema,
  linkImagem: urlImagemSchema,
  universo: Yup.string(),
  tipo: Yup.string(),
  intensidade: Yup.number().integer().min(0).nullable(),
  raridade: Yup.string(),
  tags: descricaoSchema,
  deck: Yup.string(),
  peso: Yup.number().integer().min(0).nullable(),
  cd: Yup.number().integer().min(0).nullable(),
  descricaoGeral: descricaoSchema,
  comoApresentar: descricaoSchema,
  mecanicasDesafios: descricaoSchema,
  seConseguirem: descricaoSchema,
  seFalharem: descricaoSchema,
  recompensas: descricaoSchema,
  impactoMundo: descricaoSchema,
  ganchosNarrativos: descricaoSchema,
  encadeamentoAtivo: Yup.boolean(),
  tipoAtivacao: Yup.string(),
  porcentagem: Yup.number().min(0).max(100).nullable(),
  cartasVinculadas: Yup.array(),
  descricaoEncadeamento: descricaoSchema,
});

export const CARDFLUX_INITIAL_VALUES = {
  nome: '',
  linkImagem: '',
  universo: '',
  tipo: '',
  intensidade: '',
  raridade: '',
  tags: '',
  deck: '',
  peso: '',
  cd: '',
  descricaoGeral: '',
  comoApresentar: '',
  mecanicasDesafios: '',
  seConseguirem: '',
  seFalharem: '',
  recompensas: '',
  impactoMundo: '',
  ganchosNarrativos: '',
  encadeamentoAtivo: false,
  tipoAtivacao: '',
  porcentagem: 0,
  cartasVinculadas: [],
  descricaoEncadeamento: '',
};
