import * as Yup from 'yup';

export const CARDFLUX_SCHEMA = Yup.object({
  nome: Yup.string().required('Nome é obrigatório'),
  linkImagem: Yup.string(),
  universo: Yup.string(),
  tipo: Yup.string(),
  intensidade: Yup.number().integer().min(0).nullable(),
  raridade: Yup.string(),
  tags: Yup.string(),
  deck: Yup.string(),
  peso: Yup.number().integer().min(0).nullable(),
  cd: Yup.number().integer().min(0).nullable(),
  descricaoGeral: Yup.string(),
  comoApresentar: Yup.string(),
  mecanicasDesafios: Yup.string(),
  seConseguirem: Yup.string(),
  seFalharem: Yup.string(),
  recompensas: Yup.string(),
  impactoMundo: Yup.string(),
  ganchosNarrativos: Yup.string(),
  encadeamentoAtivo: Yup.boolean(),
  tipoAtivacao: Yup.string(),
  porcentagem: Yup.number().min(0).max(100).nullable(),
  cartasVinculadas: Yup.array(),
  descricaoEncadeamento: Yup.string(),
});

export const CARDFLUX_INITIAL_VALUES = {
  nome: '',
  linkImagem: '',
  universo: '',
  tipo: '',
  intensidade: '',
  raridade: '',
  tags: '',
  deck: '',
  peso: '',
  cd: '',
  descricaoGeral: '',
  comoApresentar: '',
  mecanicasDesafios: '',
  seConseguirem: '',
  seFalharem: '',
  recompensas: '',
  impactoMundo: '',
  ganchosNarrativos: '',
  encadeamentoAtivo: false,
  tipoAtivacao: '',
  porcentagem: 0,
  cartasVinculadas: [],
  descricaoEncadeamento: '',
};
