export const ROUTE_PATHS = {
  RECURSOS: '/recursos',
  RACAS: '/recursos/racas',
  NOVA_RACA: '/recursos/racas/nova',
  ITENS: '/recursos/itens',
  NOVO_ITEM: '/recursos/itens/novo',
  MATERIAIS: '/recursos/materiais',
  NOVO_MATERIAL: '/recursos/materiais/novo',
  CLASSES: '/recursos/classes',
  NOVA_CLASSE: '/recursos/classes/nova',
  RECEITAS: '/recursos/receitas',
  NOVA_RECEITA: '/recursos/receitas/nova',
  CONDICOES: '/recursos/condicoes',
  NOVA_CONDICAO: '/recursos/condicoes/nova',
  ARTES: '/recursos/artes',
  NOVA_ARTE: '/recursos/artes/nova',
  ORIGENS: '/recursos/origens',
  NOVA_ORIGEM: '/recursos/origens/nova',
  CARDFLUX: '/recursos/cardflux',
  NOVO_CARDFLUX: '/recursos/cardflux/novo',
  REGRAS: '/regras',
  NOVA_REGRA: '/regras/nova',
  VEIAS_ASTRAIS: '/recursos/veias-astrais',
  NOVA_VEIA_ASTRAL: '/recursos/veias-astrais/nova',
  DIVINDADES: '/recursos/divindades',
  NOVA_DIVINDADE: '/recursos/divindades/nova',
  APTIDOES: '/recursos/aptidoes',
  NOVA_APTIDAO: '/recursos/aptidoes/nova',
  CORPOS_ESPECIAIS: '/recursos/corpos-especiais',
  NOVO_CORPO_ESPECIAL: '/recursos/corpos-especiais/novo',
  REINOS_CULTIVO: '/recursos/reinos-cultivo',
  NOVO_REINO_CULTIVO: '/recursos/reinos-cultivo/novo',
  PATCH_NOTES: '/patch-notes',
  SOBRE: '/sobre',
};

export const PAGE_TITLES = {
  [ROUTE_PATHS.RECURSOS]: 'Recursos',
  [ROUTE_PATHS.RACAS]: 'Raças',
  [ROUTE_PATHS.NOVA_RACA]: 'Nova Raça',
  [ROUTE_PATHS.ITENS]: 'Itens',
  [ROUTE_PATHS.NOVO_ITEM]: 'Novo Item',
  [ROUTE_PATHS.MATERIAIS]: 'Materiais',
  [ROUTE_PATHS.NOVO_MATERIAL]: 'Novo Material',
  [ROUTE_PATHS.CLASSES]: 'Classes',
  [ROUTE_PATHS.NOVA_CLASSE]: 'Nova Classe',
  [ROUTE_PATHS.RECEITAS]: 'Receitas',
  [ROUTE_PATHS.NOVA_RECEITA]: 'Nova Receita',
  [ROUTE_PATHS.CONDICOES]: 'Condições',
  [ROUTE_PATHS.NOVA_CONDICAO]: 'Nova Condição',
  [ROUTE_PATHS.ARTES]: 'Artes',
  [ROUTE_PATHS.NOVA_ARTE]: 'Nova Arte',
  [ROUTE_PATHS.ORIGENS]: 'Origens',
  [ROUTE_PATHS.NOVA_ORIGEM]: 'Nova Origem',
  [ROUTE_PATHS.CARDFLUX]: 'CardFlux',
  [ROUTE_PATHS.NOVO_CARDFLUX]: 'Novo CardFlux',
  [ROUTE_PATHS.REGRAS]: 'Regras',
  [ROUTE_PATHS.NOVA_REGRA]: 'Nova Regra',
  [ROUTE_PATHS.VEIAS_ASTRAIS]: 'Veias Astrais',
  [ROUTE_PATHS.NOVA_VEIA_ASTRAL]: 'Nova Veia Astral',
  [ROUTE_PATHS.DIVINDADES]: 'Divindades',
  [ROUTE_PATHS.NOVA_DIVINDADE]: 'Nova Divindade',
  [ROUTE_PATHS.APTIDOES]: 'Aptidões',
  [ROUTE_PATHS.NOVA_APTIDAO]: 'Nova Aptidão',
  [ROUTE_PATHS.CORPOS_ESPECIAIS]: 'Corpos Especiais',
  [ROUTE_PATHS.NOVO_CORPO_ESPECIAL]: 'Novo Corpo Especial',
  [ROUTE_PATHS.REINOS_CULTIVO]: 'Reinos de Cultivo',
  [ROUTE_PATHS.NOVO_REINO_CULTIVO]: 'Novo Reino de Cultivo',
  [ROUTE_PATHS.PATCH_NOTES]: 'Patch Notes',
  [ROUTE_PATHS.SOBRE]: 'Sobre',
};
