export const ROUTE_PATHS = {
  MESAS: '/mesas',
  MUNDO: '/mundo',
  NPCS: '/npcs',
  RECURSOS: '/recursos',
  RACAS: '/recursos/racas',
  NOVA_RACA: '/recursos/racas/nova',
  ITENS: '/recursos/itens',
  NOVO_ITEM: '/recursos/itens/novo',
  MATERIAIS: '/recursos/materiais',
  NOVO_MATERIAL: '/recursos/materiais/novo',
  CLASSES: '/recursos/classes',
  NOVA_CLASSE: '/recursos/classes/nova',
  RECEITAS: '/recursos/receitas',
  NOVA_RECEITA: '/recursos/receitas/nova',
  CONDICOES: '/recursos/condicoes',
  NOVA_CONDICAO: '/recursos/condicoes/nova',
  ARTES: '/recursos/artes',
  NOVA_ARTE: '/recursos/artes/nova',
  ORIGENS: '/recursos/origens',
  NOVA_ORIGEM: '/recursos/origens/nova',
  REGRAS: '/regras',
  NOVA_REGRA: '/regras/nova',
  MACROS: '/macros',
  PATCH_NOTES: '/patch-notes',
  NUCLEO: '/nucleo',
  SOBRE: '/sobre',
};

export const PAGE_TITLES = {
  [ROUTE_PATHS.MESAS]: 'Mesas',
  [ROUTE_PATHS.MUNDO]: 'World',
  [ROUTE_PATHS.NPCS]: 'NPCs',
  [ROUTE_PATHS.RECURSOS]: 'Recursos',
  [ROUTE_PATHS.RACAS]: 'Raças',
  [ROUTE_PATHS.NOVA_RACA]: 'Nova Raça',
  [ROUTE_PATHS.ITENS]: 'Itens',
  [ROUTE_PATHS.NOVO_ITEM]: 'Novo Item',
  [ROUTE_PATHS.MATERIAIS]: 'Materiais',
  [ROUTE_PATHS.NOVO_MATERIAL]: 'Novo Material',
  [ROUTE_PATHS.CLASSES]: 'Classes',
  [ROUTE_PATHS.NOVA_CLASSE]: 'Nova Classe',
  [ROUTE_PATHS.RECEITAS]: 'Receitas',
  [ROUTE_PATHS.NOVA_RECEITA]: 'Nova Receita',
  [ROUTE_PATHS.CONDICOES]: 'Condições',
  [ROUTE_PATHS.NOVA_CONDICAO]: 'Nova Condição',
  [ROUTE_PATHS.ARTES]: 'Artes',
  [ROUTE_PATHS.NOVA_ARTE]: 'Nova Arte',
  [ROUTE_PATHS.ORIGENS]: 'Origens',
  [ROUTE_PATHS.NOVA_ORIGEM]: 'Nova Origem',
  [ROUTE_PATHS.REGRAS]: 'Regras',
  [ROUTE_PATHS.NOVA_REGRA]: 'Nova Regra',
  [ROUTE_PATHS.MACROS]: 'Macros',
  [ROUTE_PATHS.PATCH_NOTES]: 'Patch Notes',
  [ROUTE_PATHS.NUCLEO]: 'Núcleo',
  [ROUTE_PATHS.SOBRE]: 'Sobre',
};
