export const ROUTE_PATHS = {
  MESAS: '/mesas',
  MUNDO: '/mundo',
  NPCS: '/npcs',
  RECURSOS: '/recursos',
  RACAS: '/recursos/racas',
  NOVA_RACA: '/recursos/racas/nova',
  ITENS: '/recursos/itens',
  NOVO_ITEM: '/recursos/itens/novo',
  MATERIAIS: '/recursos/materiais',
  NOVO_MATERIAL: '/recursos/materiais/novo',
  CLASSES: '/recursos/classes',
  NOVA_CLASSE: '/recursos/classes/nova',
  REGRAS: '/regras',
  MACROS: '/macros',
  PATCH_NOTES: '/patch-notes',
  NUCLEO: '/nucleo',
  SOBRE: '/sobre',
};

export const PAGE_TITLES = {
  [ROUTE_PATHS.MESAS]: 'Mesas',
  [ROUTE_PATHS.MUNDO]: 'World',
  [ROUTE_PATHS.NPCS]: 'NPCs',
  [ROUTE_PATHS.RECURSOS]: 'Recursos',
  [ROUTE_PATHS.RACAS]: 'Raças',
  [ROUTE_PATHS.NOVA_RACA]: 'Nova Raça',
  [ROUTE_PATHS.ITENS]: 'Itens',
  [ROUTE_PATHS.NOVO_ITEM]: 'Novo Item',
  [ROUTE_PATHS.MATERIAIS]: 'Materiais',
  [ROUTE_PATHS.NOVO_MATERIAL]: 'Novo Material',
  [ROUTE_PATHS.CLASSES]: 'Classes',
  [ROUTE_PATHS.NOVA_CLASSE]: 'Nova Classe',
  [ROUTE_PATHS.REGRAS]: 'Regras',
  [ROUTE_PATHS.MACROS]: 'Macros',
  [ROUTE_PATHS.PATCH_NOTES]: 'Patch Notes',
  [ROUTE_PATHS.NUCLEO]: 'Núcleo',
  [ROUTE_PATHS.SOBRE]: 'Sobre',
};
